In [2]:
import pandas as pd

In [3]:
import sklearn as sk

In [4]:
df=pd.read_excel("OverallFY 22-23.xlsx",sheet_name=2)

In [5]:
df

,SNO,Collection Partner,City,State,Category (1/2/3/4),Month,Vehicle No.,Dispatch Qty,Dispatch Date,Received Qty,Received Date,Qty Diff,Qty Diff %,PWPF name,PWPF Location,Mode of Disposal,Brand Name
0,1,Rahim,Mumbai,Maharashtra,Category 2,January,MH04FD3178,11.54,2023-01-07 00:00:00,11.510,2023-01-07 00:00:00,-0.030,-0.259965,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
1,2,Salman,Mumbai,Maharashtra,Category 2,January,MH12DG8721,3.18,2023-01-08 00:00:00,3.180,2023-01-08 00:00:00,0.000,0.000000,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
2,3,Sohel,Mumbai,Maharashtra,Category 2,January,MH04HD3453,6.92,2023-01-09 00:00:00,6.895,2023-01-09 00:00:00,-0.025,-0.361272,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
3,4,Rizwan,Mumbai,Maharashtra,Category 2,January,MH04FD5355,14.43,2023-01-10 00:00:00,14.385,2023-01-10 00:00:00,-0.045,-0.311850,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
4,5,Shree Ganesh Polymers,Chitradurga,Karnataka,Category 1,January,HR39E3660,15.94,2023-01-05 00:00:00,15.920,2023-01-07 00:00:00,-0.020,-0.125471,Badri Cotsyn Pvt Ltd.,Madhya Pradesh,Recycling,AGILENT TECHNOLOGY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5314,5315,Swachh Sustainable Solutions Pvt Ltd,Mumbai,Maharashtra,Category 3,November,KA32D5725,7600.00,2022-11-18 00:00:00,7590.000,2022-11-19 00:00:00,-10.000,-0.131579,Rajashree Cement Works,Karnataka,Co-Processing,TATA STARBUCKS
5315,5316,Swachh Sustainable Solutions Pvt Ltd,Mumbai,Maharashtra,Category 3,November,KA28AA1850,9540.00,2022-11-18 00:00:00,9520.000,2022-11-20 00:00:00,-20.000,-0.209644,Rajashree Cement Works,Karnataka,Co-Processing,TATA STARBUCKS
5316,5317,Swachh Sustainable Solutions Pvt Ltd,Mumbai,Maharashtra,Category 3,November,KA32D5725,8680.00,2022-11-22 00:00:00,8600.000,2022-11-23 00:00:00,-80.000,-0.921659,Rajashree Cement Works,Karnataka,Co-Processing,TATA STARBUCKS
5317,5318,Swachh Sustainable Solutions Pvt Ltd,Tezpur,Assam,Category 3,December,AS01LC4058,19950.00,2022-12-24 00:00:00,19620.000,2022-12-24 00:00:00,-330.000,-1.654135,Dalmia Cement Bharat Ltd,Meghalaya,Co-Processing,TATA STARBUCKS
5318,5319,Zero Waste Management Llp,Vapi,Gujarat,Category 2,December,GJ05CU5068,8420.00,2022-12-30 00:00:00,8370.000,2022-12-31 00:00:00,-50.000,-0.593824,Earth Enviro Wastocare,Rajkot,Recycling,TATA STARBUCKS

In [6]:
df.shape

(5319, 17)

In [7]:
df["Dispatch Qty"]

0          11.54
1           3.18
2           6.92
3          14.43
4          15.94
          ...
5314     7600.00
5315     9540.00
5316     8680.00
5317    19950.00
5318     8420.00
Name: Dispatch Qty, Length: 5319, dtype: float64

In [8]:
import seaborn as sn

In [9]:
import numpy as np

In [10]:
q1=np.percentile(df["Dispatch Qty"],25,method='midpoint')
q3=np.percentile(df["Dispatch Qty"],75,method='midpoint')

In [11]:
iqr=q3-q1

In [12]:
iqr

9.6425

In [13]:
upper=q3+1.5*iqr
lower=q1-1.5*iqr

In [14]:
upper_arr=np.where(df["Dispatch Qty"]>=upper)[0]
lower_arr=np.where(df["Dispatch Qty"]<=lower)[0]

In [15]:
df.drop(index=upper_arr,inplace=True)
df.drop(index=lower_arr,inplace=True)

In [16]:
df.shape

(5224, 17)

In [18]:
df["Dispatch Qty"]

0       11.54
1        3.18
2        6.92
3       14.43
4       15.94
        ...
5303    18.13
5304    18.18
5305    16.98
5306    19.72
5307    21.39
Name: Dispatch Qty, Length: 5224, dtype: float64

In [19]:
df.describe()

               SNO  Dispatch Qty  Received Qty      Qty Diff     Qty Diff %
count  5224.000000   5224.000000   5224.000000   5224.000000    5224.000000
mean   2644.896631     12.239963     78.348387     66.108424     320.294004
std    1524.768263      6.198403   1192.986265   1192.435382    5609.157781
min       1.000000      0.305000      0.310000     -5.190000     -25.376884
25%    1310.750000      7.363750      7.357500     -0.050000      -0.427991
50%    2654.500000     12.020000     12.010000     -0.020000      -0.174490
75%    3965.250000     16.672500     16.580000      0.000000       0.000000
max    5308.000000     31.530000  28600.000000  28571.510000  100286.100386

In [25]:
df_cp=df[["Collection Partner","City",'State','Category (1/2/3/4)','Month',"Dispatch Qty",'PWPF name','PWPF Location','Mode of Disposal', 'Brand Name']]

In [29]:
from geopy.geocoders import Nominatim
geolocator=Nominatim(user_agent="Geopy library")
lat_arr=[]
long_arr=[]
try:
    for city in df["State"]:
        print(city)
        lat_long_coords = geolocator.geocode(city)
        lat_arr.append(lat_long_coords.raw['lat'])
        long_arr.append(lat_long_coords.raw['lon'])
except AttributeError:
    print("EMpty")
finally

Maharashtra
Maharashtra
Maharashtra
Maharashtra
Karnataka
Maharashtra
Maharashtra
Delhi
Maharashtra
Maharashtra
Maharashtra
Maharashtra
Maharashtra
Maharashtra
Maharashtra
Maharashtra
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Rajasthan
Manipur
Manipur
Nagaland
Nagaland
Sikkim
Bihar
Bihar
Bihar
Bihar
Bihar
Assam
Assam
Assam
Assam
Assam
Sikkim
Sikkim
Sikkim
Nagaland
Nagaland
Manipur
Manipur
Manipur
Assam
Assam
Assam
Bihar
Bihar
Bihar
Bihar
Bihar
Bihar
Bihar
Bihar
Assam
Assam
Assam
Assam
Assam
Assam
Assam
Assam
Assam
Assam
Assam
Meghalaya
Meghalaya
Nagaland
Mizoram
Agartala
Sikkim
Manipur
Arunachal Pradesh
Arunachal Pradesh
Uttarakhand
Rajasthan
Rajasthan
Rajasthan
Daman & Diu and Dadar & Nagar Haveli
EMpty

In [26]:
df_cp

,Collection Partner,City,State,Category (1/2/3/4),Month,Dispatch Qty,PWPF name,PWPF Location,Mode of Disposal,Brand Name
0,Rahim,Mumbai,Maharashtra,Category 2,January,11.54,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
1,Salman,Mumbai,Maharashtra,Category 2,January,3.18,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
2,Sohel,Mumbai,Maharashtra,Category 2,January,6.92,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
3,Rizwan,Mumbai,Maharashtra,Category 2,January,14.43,Rajasthan Plastic Industries,Malegaon,Recycling,AGILENT TECHNOLOGY
4,Shree Ganesh Polymers,Chitradurga,Karnataka,Category 1,January,15.94,Badri Cotsyn Pvt Ltd.,Madhya Pradesh,Recycling,AGILENT TECHNOLOGY
...,...,...,...,...,...,...,...,...,...,...
5303,Swachh Sustainable Solutions Pvt Ltd,South Delhi,New Delhi,Category 3,November,18.13,Rollz India Waste Management Pvt Ltd,Uttar Pradesh,Co-Processing,NESTLE INDIA
5304,Swachh Sustainable Solutions Pvt Ltd,South Delhi,New Delhi,Category 3,November,18.18,Rollz India Waste Management Pvt Ltd,Uttar Pradesh,Co-Processing,NESTLE INDIA
5305,Swachh Sustainable Solutions Pvt Ltd,South Delhi,New Delhi,Category 3,November,16.98,Rollz India Waste Management Pvt Ltd,Uttar Pradesh,Co-Processing,NESTLE INDIA
5306,Swachh Sustainable Solutions Pvt Ltd,South Delhi,New Delhi,Category 3,November,19.72,Rollz India Waste Management Pvt Ltd,Uttar Pradesh,Co-Processing,NESTLE INDIA
5307,Swachh Sustainable Solutions Pvt Ltd,South Delhi,New Delhi,Category 3,November,21.39,Rollz India Waste Management Pvt Ltd,Uttar Pradesh,Co-Processing,NESTLE INDIA